### ISSUE TITLE
Issue with default scrollStrategy

### ISSUE THREAD

**Issue by julianobrasil** [ncsu-sat/popover#56]
As I understood from README, by default, when popover is visible and you scroll the background, it should stay attached to the anchor, repositioning itself. It worked just fine when I tested it in stackblitz.

In one page I used it, for some reason it didn't stay attached to the anchor.  It seems to be attatched to mouse position as I scrooll the background using the mouse wheel. I couldn't isolate the cause yet nor reproduce it in stackblitz.

If I have any progress with reproducing it, I'll let you know.

**Comment by willshowell** [comment]
Is it consistent on that one page? Gif/video? And is it hover or click and on what kind of anchor?

Also yeah it's always reposition in beta.0 but you'll have the option to block in the next release!

**Comment by julianobrasil** [comment]
In fact, I wanted the default behavior.

I don't have any gif/video because when I started oCam it interfered with the issue (it doesn't fix it, but it behaves different). I'll post a gif anyway in a few minutes (just trying some styling in popover).

It's on hover event.

**Comment by julianobrasil** [comment]
Here it is. BTW, it's anchored in a regular div. Maybe the overall structure of the page is causing it. It's a `flex-layout` item and inside it there's a `<mat-list>`. I tried to take away `<mat-list>` and use a simple text instead of it, but the issue remained. Dispite the fact that oCam is messing a little with the behavior I'm seeing, basically it seems that when I scroll the page, the popover takes around 1 sec to close.

![image](https://media.giphy.com/media/3ov9jL67yIO9OpGyOs/giphy.gif)

The popover is basically:

```html
<div [satPopoverAnchorFor]="popover" (mouseenter)="popover.open()" (mouseleave)="popover.close()">Legenda</div>

<sat-popover #popover xPosition="after" [overlapAnchor]="false">
  <div class="popover-class">
    <mat-list>
      <h3 mat-subheader [style.color]="'white'">Legenda</h3>
      <mat-list-item>
        <mat-icon mat-list-icon>spellcheck</mat-icon>
        <p mat-line class="mat-caption"> Indicador possui ação cadastrada</p>
      </mat-list-item>
      <mat-list-item>
        <mat-icon mat-list-icon [style.color]="'#ffeeba'">format_color_fill</mat-icon>
        <p mat-line class="mat-caption"> Desempenho abaixo da meta</p>
      </mat-list-item>
    </mat-list>
  </div>
</sat-popover>
```

**Comment by willshowell** [comment]
Your video definitely looks like `mouseleave` is not firing until later. Is that because of oCam or is that the usual behavior? And can you verify it by wrapping the `popover.close` and including a console.log?

Another troubleshooting measure may be to switch to `(click)="popover.toggle()` to see if repositioning can still work like that.

**Comment by julianobrasil** [comment]
Take a look at the results.

### `(click)="popover.toggle()"`

![image](https://media.giphy.com/media/3ov9jU4fyzZ3KQ1LiM/giphy.gif)

### wrapping the `popover.close` and including a `console.log`

In this case, clearly the (mouseleave) is beeing fired after I stop scrolling _and_ move the mouse again.

![image](https://media.giphy.com/media/3ov9k94fnsrN4iPT5C/giphy.gif)

**Comment by willshowell** [comment]
Is the scrolling happening on the body or some other container (like a sidenav container)? I wonder if applying [`cdkScrollable`](https://material.angular.io/cdk/scrolling/overview#cdkscrollable-and-scrolldispatcher) to the scrolling container would fix it... I haven't seen any issues locally yet, but I've just been scrolling the body in all my tests.

Also I'll try to get the next release out early this week and you can see if the block/noop behaviors behave differently.

**Comment by willshowell** [comment]
And if you really want to dig into it... 😄 

1. Open `node_modules/@angular/cdk/esm5/overlay.es5.js`
2. Find this section,

    ```js
    RepositionScrollStrategy.prototype.enable = function () {
        var _this = this;
        if (!this._scrollSubscription) {
            var /** @type {?} */ throttle = this._config ? this._config.scrollThrottle : 0;
            this._scrollSubscription = this._scrollDispatcher.scrolled(throttle, function () {
                _this._overlayRef.updatePosition();
            });
        }
    };
    ```
3. Add a console.log before `_this._overlayRef.updatePosition()`
4. If it's not being called, then it's likely something that we can fix by applying `cdkScrollable` (or identifying a cdk bug?)
5. If it is being called, then maybe there's a bug in the popover position strategy that we can fix.

**Comment by julianobrasil** [comment]
> Is the scrolling happening on the body or some other container

Other container. I have a menu bar on the top that cannot be a part of the scrollable region

The first thing I'll try out is the `cdkScrollable`. Then I'll take a deeper look into the file you suggested.

**Comment by julianobrasil** [comment]
`cdkScrollable solved it` 😃

**Comment by willshowell** [comment]
Great! I'll make a note to add that to the readme

**Comment by julianobrasil** [comment]
Yeah... it's a important note.

**Comment by VitaliyOnRule** [comment]
> `cdkScrollable` solved it

I have the same problem and how 'cdkScrollable' should be implemented to solve it?
